---
name: Publish

on:
  release:
    types:
      - published

env:
  CACHE_VERSION: v1
  ELIXIR_VERSION: "1.13"
  OTP_VERSION: "25"

jobs:
  Hex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: stordco/actions-elixir/setup@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          hex-token: ${{ secrets.HEX_API_KEY }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Compile
        run: mix compile --docs

      - name: Publish
        run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
